window.env = {
    HOURLY_REPORT_EMPLOYEE_NAME: $env.HOURLY_REPORT_EMPLOYEE_NAME,
    HOURLY_REPORT_PERIOD: $env.HOURLY_REPORT_PERIOD,
    HOURLY_REPORT_TABLE_ROWS: $env.HOURLY_REPORT_TABLE_ROWS,
    HOURLY_REPORT_TOTAL_HOURS: $env.HOURLY_REPORT_TOTAL_HOURS,
}