version: '3'

services:
    time-tracker:
        build: .
        networks:
            - postgres_database
        # depends_on:
        #     - postgres
        ports:
            - 3000:3000
        environment: 
            - ENCRYPTION_KEY=uMlZlHeAEU3w3X+sDQLT9Q==
            - POSTGRES_USER=admin
            - POSTGRES_HOST=postgres
            - POSTGRES_PORT=5432
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=time-tracker
            - PGADMIN_DEFAULT_EMAIL=admin@admin.com
            - PGADMIN_DEFAULT_PASSWORD=admin
networks: 
    postgres_database:
        external: true
        
    # postgres:
    #     image: postgres:11.5
    #     ports:
    #         - "5432:5432"
    #     volumes:
    #         - /data/postgres:/data/postgres
    #     environment:
    #         - POSTGRES_USER=admin
    #         - POSTGRES_PASSWORD=admin
    #         - POSTGRES_DB=time-tracker
    #         - PGADMIN_DEFAULT_EMAIL=admin@admin.com
    #         - PGADMIN_DEFAULT_PASSWORD=admin  