version: '3'

services:
    time-tracker:
        build: .
        depends_on:
            - postgres
        ports:
            - 3000:3000
        environment: 
            - POSTGRES_USER=admin
            - POSTGRES_HOST=postgres
            - POSTGRES_PORT=5432
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=tutorial
            - PGADMIN_DEFAULT_EMAIL=admin@admin.com
            - PGADMIN_DEFAULT_PASSWORD=admin
        networks:
            - postgres
        
    postgres:
        image: postgres:latest
        ports:
            - "5432:5432"
        volumes:
            - /data/postgres:/data/postgres
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=tutorial
            - PGADMIN_DEFAULT_EMAIL=admin@admin.com
            - PGADMIN_DEFAULT_PASSWORD=admin
        networks:
        - postgres

networks:
  postgres:
    driver: bridge