swagger: '2.0'
info:
  version: 1.0.0
  title: Time Tracker API
  description: API for the Time Tracker App
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
host: 'localhost:3000'
basePath: /api
tags:
  - name: Users
    description: API for users in the system
  - name: Portfolios
    description: API for users' portfolios
  - name: Auth
    description: API for user access management
schemes:
  - http
securityDefinitions:
  basicAuth:
    type: basic
consumes:
  - application/json
produces:
  - application/json
paths:
  /auth/login:
    post:
      tags:
        - Auth
      description: Login User
      parameters:
        - name: user
          in: body
          description: User to login
          schema:
            $ref: '#/definitions/UserLoginRequest'
      produces:
        - application/json
      responses:
        '200':
          description: New portfolio is created
          schema:
            $ref: '#/definitions/TokenResponse'
        '400':
          description: Incomplete request
        '401':
          description: Unauthorized
        '404':
          description: User not found
        '500':
          description: Something went wrong
  /auth/register:
    post:
      tags:
        - Auth
      description: Create new user in system
      parameters:
        - name: user
          in: body
          description: User that we want to create
          schema:
            $ref: '#/definitions/UserCreate'
      produces:
        - application/json
      responses:
        '200':
          description: New user is created
          schema:
            $ref: '#/definitions/TokenResponse'
        '400':
          description: Incomplete request
        '409':
          description: User already exists
        '500':
          description: Something went wrong
  /users:
    parameters:
      - name: Authorization
        in: header
        type: string
        required: true
    get:
      tags:
        - Users
      summary: Get all users in system
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/UsersWithNoPasswordResponse'
        '500':
          description: Something went wrong
  '/users/{userId}':
    parameters:
      - name: userId
        in: path
        required: true
        description: ID of user that we want to find
        type: string
      - name: Authorization
        in: header
        type: string
        required: true
    get:
      tags:
        - Users
      summary: Get user with given ID
      responses:
        '200':
          description: User is found
          schema:
            $ref: '#/definitions/UserWithNoPasswordResponse'
        '500':
          description: Something went wrong
    delete:
      summary: Delete user with given ID
      tags:
        - Users
      responses:
        '200':
          description: User is deleted
          schema:
            $ref: '#/definitions/UserWithNoPasswordResponse'
        '500':
          description: Something went wrong
definitions:
  UserCreate:
    required:
      - username
      - password
    properties:
      email:
        type: string
        uniqueItems: true
      username:
        type: string
        uniqueItems: true
      password:
        type: string
  UserWithNoPasswordResponse:
    required:
      - username
      - password
    properties:
      email:
        type: string
        uniqueItems: true
      username:
        type: string
        uniqueItems: true
  UsersWithNoPasswordResponse:
    type: array
    items:
      $ref: '#/definitions/UserWithNoPasswordResponse'
  UserLoginRequest:
    required:
      - username
      - password
    properties:
      username:
        type: string
        uniqueItems: true
      password:
        type: string
  TokenResponse:
    properties:
      auth:
        type: boolean
      token:
        type: string
