window.env = {
    INVOICE_CUSTOMER_NAME: "Spectrio",
    INVOICE_CUSTOMER_ADDRESS_LINE_1: "1201 Story avenue",
    INVOICE_CUSTOMER_ADDRESS_LINE_2: "#400",
    INVOICE_CUSTOMER_ADDRESS_LINE_3: "Louisville, KY 40206",
    INVOICE_NUMBER: "undefined",
    INOVICE_DATE: "undefined",
    INOVICE_DUE_DATE: "undefined",
    INOVICE_TERMS: "undefined",
    INOVICE_DESCRIPTION_LIST: "undefined",
    INOVICE_QUANTITY_LIST: "undefined",
    INOVICE_RATE_LIST: "undefined",
    INOVICE_AMOUNT_LIST: "undefined",
    INOVICE_TOTAL: "undefined",
}