window.env = {
    INVOICE_CUSTOMER_NAME: $env.INVOICE_CUSTOMER_NAME,
    INVOICE_CUSTOMER_ADDRESS_LINE_1: $env.INVOICE_CUSTOMER_ADDRESS_LINE_1,
    INVOICE_CUSTOMER_ADDRESS_LINE_2: $env.INVOICE_CUSTOMER_ADDRESS_LINE_2,
    INVOICE_CUSTOMER_ADDRESS_LINE_3: $env.INVOICE_CUSTOMER_ADDRESS_LINE_3,
    INVOICE_NUMBER: $env.INVOICE_NUMBER,
    INOVICE_DATE: $env.INOVICE_DATE,
    INOVICE_DUE_DATE: $env.INOVICE_DUE_DATE,
    INOVICE_TERMS: $env.INOVICE_TERMS,
    INOVICE_DESCRIPTION_LIST: $env.INOVICE_DESCRIPTION_LIST,
    INOVICE_QUANTITY_LIST: $env.INOVICE_QUANTITY_LIST,
    INOVICE_RATE_LIST: $env.INOVICE_RATE_LIST,
    INOVICE_AMOUNT_LIST: $env.INOVICE_AMOUNT_LIST,
    INOVICE_TOTAL: $env.INOVICE_TOTAL
}