window.env = {
    INVOICE_CUSTOMER_NAME: $env.INVOICE_CUSTOMER_NAME,
    INVOICE_CUSTOMER_ADDRESS_LINE_1: $env.INVOICE_CUSTOMER_ADDRESS_LINE_1,
    INVOICE_CUSTOMER_ADDRESS_LINE_2: $env.INVOICE_CUSTOMER_ADDRESS_LINE_2,
    INVOICE_CUSTOMER_ADDRESS_LINE_3: $env.INVOICE_CUSTOMER_ADDRESS_LINE_3,
    INVOICE_NUMBER: $env.INVOICE_NUMBER,
    INVOICE_DATE: $env.INVOICE_DATE,
    INVOICE_DUE_DATE: $env.INVOICE_DUE_DATE,
    INVOICE_TERMS: $env.INVOICE_TERMS,
    INVOICE_DESCRIPTION_LIST: $env.INVOICE_DESCRIPTION_LIST,
    INVOICE_QUANTITY_LIST: $env.INVOICE_QUANTITY_LIST,
    INVOICE_RATE_LIST: $env.INVOICE_RATE_LIST,
    INVOICE_AMOUNT_LIST: $env.INVOICE_AMOUNT_LIST,
    INVOICE_TOTAL: $env.INVOICE_TOTAL
}